name: urgent_daily
description: "Your Daily Urgency organized!"

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  table_calendar: ^3.1.2
  auto_injector: ^2.0.5
  uuid: ^4.5.1
  firebase_core: ^3.8.0
  flutter_dotenv: ^5.2.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.6.6
  google_sign_in: ^6.2.2
  google_sign_in_web: ^0.12.4+3

  abelliz_essentials:
    path: "../abelliz_essentials"

  mobkit_dashed_border: any
  firebase_app_check: ^0.3.2+5
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_launcher_icons: ^0.14.3

  flutter_flavorizr: ^2.2.3
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#8fd14f"
    theme_color: "#8fd14f"

flavorizr:
  app:
    ios:
      flavorDimensions: "dev"
  flavors:
    dev:
      app:
        name: "UrgentDaily"
      ios:
        bundleId: "com.abelli.urgentdaily"
        firebase:
          config: "ios/Flutter/GoogleService-Info.plist"
